// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgABRZozzGHALXYLf-ZOOXzj3CoMXIvok',
    appId: '1:32689302493:web:419a9f21edfe0b1e662434',
    messagingSenderId: '32689302493',
    projectId: 'flutter-chat-a3bb2',
    authDomain: 'flutter-chat-a3bb2.firebaseapp.com',
    storageBucket: 'flutter-chat-a3bb2.appspot.com',
    measurementId: 'G-1YFLG3ZT63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdEQ024FlinCfiVcqWvBVOnLxqvU7OCuc',
    appId: '1:32689302493:android:7bd3f6b00eaaa5bd662434',
    messagingSenderId: '32689302493',
    projectId: 'flutter-chat-a3bb2',
    storageBucket: 'flutter-chat-a3bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zzNEvmCSfN0FmLR3PAnDwYeiR6jQP4Y',
    appId: '1:32689302493:ios:56545aa0c10609b1662434',
    messagingSenderId: '32689302493',
    projectId: 'flutter-chat-a3bb2',
    storageBucket: 'flutter-chat-a3bb2.appspot.com',
    iosClientId: '32689302493-mmm3n0ugq1qh1i2atct3au4681u0kdde.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
